-- loginuser
INSERT INTO loginuser (userName, password, preferredLanguage) VALUES 
('super', 'super', 'nl'),
('test1', 'test1', 'nl'),
('test2', 'test2', 'nl'),
('test3', 'test3', 'nl'),
('test4', 'test4', 'nl'),
('test5', 'test5', 'nl'),
('test6', 'test6', 'nl'),
('test7', 'test7', 'nl'),
('test8', 'test8', 'nl'),
('test9', 'test9', 'nl')
;
DELETE FROM Translation WHERE id > 0
;
-- Translations
INSERT INTO Translation (`group`, `key`, language, text) VALUES 
( 'GAME_STATUS', 'AVAILABLE', 'nl', 'Beschikbaar' ),
( 'GAME_STATUS', 'CALCULATING', 'nl', 'Aan het rekenen' ),
( 'GAME_STATUS', 'FINISHED', 'nl', 'Afgerond' ),
( 'CARD_STATUS', 'INITIAL', 'nl', 'Initieel' ),
( 'CARD_STATUS', 'FINAL', 'nl', 'Vastgelegd' ),
( 'CARD_STATUS', 'LOCKED', 'nl', 'Vergrendeld' ),
( 'CARD_STATUS', 'FLYWHEEL', 'nl', 'Op het vliegwiel' ),
( 'EVENT_MESSAGE', 'BOT_PUSHES', 'nl', '# duwt %' ),
( 'EVENT_MESSAGE', 'CONVEYORBELT_STALL', 'nl', '# en % staan stil op de lopende band omdat ze anders op elkaar botsen' ),
( 'EVENT_MESSAGE', 'BOT_SHOOTS', 'nl', '# raakt % met de laser' ),
( 'EVENT_MESSAGE', 'BOARD_SHOOTS', 'nl', '% wordt geraakt door een laser op het bord' ),
( 'EVENT_MESSAGE', 'BOT_DIES_DAMAGE', 'nl', '% is dood gegaan door teveel schade' ),
( 'EVENT_MESSAGE', 'BOT_DIES_HOLE', 'nl', '% is dood gegaan doordat het in een gat gekomen is' ),
( 'EVENT_MESSAGE', 'ARCHIVEMARKER_MOVED', 'nl', '# heeft een nieuwe archiveMarker op coordinaten $' ),
( 'EVENT_MESSAGE', 'POWER_DOWN', 'nl', '# powert down voor deze ronde' ),
( 'EVENT_MESSAGE', 'BOT_HITS_WALL', 'nl', '# botst tegen een muur' ),
( 'EVENT_MESSAGE', 'BOT_HITS_UNMOVABLE_BOT', 'nl', '# botst tegen % die niet geduwd kan worden' ),
( 'SCENARIO', 'MovingTargets', 'nl', 'Moving Targets (2-8, Medium lengte, Expert)' ),
( 'SCENARIO', 'Test', 'nl', 'Testscenario om alle borden te zien' ),
( 'SCENARIO', 'AgainstTheGrain', 'nl', 'Against the Grain (2-4, Medium lengte, Expert)' ),
( 'SCENARIO', 'Tricksy', 'nl', 'Tricksy (2-4, Lange lengte, Expert)' ),
( 'SCENARIO', 'IslandKing', 'nl', 'Island King (5-8, Korte lengte, Expert)' ),
( 'SCENARIO', 'OddestSea', 'nl', 'Oddest Sea (5-8, Lange lengte, Expert)' ),
( 'SCENARIO', 'RobotStew', 'nl', 'Robot Stew (2-4, Medium lengte, Expert)' ),
( 'SCENARIO', 'LostBearings', 'nl', 'Lost Bearings (2-4, Medium lengte, Expert)' ),
( 'SCENARIO', 'WhirlwindTour', 'nl', 'Whirlwind Tour (5-8, Medium lengte, Expert)' ),
( 'SCENARIO', 'VaultAssault', 'nl', 'Vault Assault (2-4, Korte lengte, Expert)' ),
( 'SCENARIO', 'Pilgrimage', 'nl', 'Pilgrimage (2-8, Lange lengte, Beginner)' ),
( 'SCENARIO', 'DeathTrap', 'nl', 'Death Trap (2-4, Korte lengte, Beginner)' ),
( 'SCENARIO', 'AroundTheWorld', 'nl', 'Around the World (5-8, Lange lengte, Beginner)' ),
( 'SCENARIO', 'BloodbathChess', 'nl', 'Bloodbath Chess (2-4, Medium lengte, Beginner)' ),
( 'SCENARIO', 'Twister', 'nl', 'Twister (5-8, Medium lengte, Beginner)' ),
( 'SCENARIO', 'ChopShopChallenge', 'nl', 'Chop Shop Challenge (2-4, Medium lengte, Beginner)' ),
( 'SCENARIO', 'IslandHop', 'nl', 'Island Hop (2-8, Medium lengte, Beginner)' ),
( 'SCENARIO', 'DizzyDash', 'nl', 'Dizzy Dash (2-8, Korte lengte, Beginner)' ),
( 'SCENARIO', 'Checkmate', 'nl', 'Checkmate (5-8, Korte lengte, Beginner)' ),
( 'SCENARIO', 'RiskyExchange', 'nl', 'Risky Exchange (2-8, Medium lengte, Beginner)' ),
( 'LANGUAGE', 'NL', 'nl', 'Nederlands' ),
( 'LANGUAGE', 'EN', 'nl', 'Engels' ),
( 'LANGUAGE', 'NL', 'en', 'Dutch' ),
( 'LANGUAGE', 'EN', 'en', 'English' )
;
